# ---------------------------------------------------------------------------
# MC-SIMEX: Monte Carlo Simulation Extrapolation for misclassified covariates
# ---------------------------------------------------------------------------

#' MC-SIMEX estimator for GLMs with misclassified covariates
#'
#' Implements the Misclassification SIMEX method of Küchenhoff, Mwalili and
#' Lesaffre (2006). The simulation step is implemented in C++ for high
#' performance. Supports Poisson, Binomial, and Gaussian GLM families.
#'
#' @param y Numeric response vector (length n).
#' @param z_hat Integer proxy covariate (values in \{0, ..., K-1\}).
#' @param x Numeric covariate matrix (n x r), including intercept if desired.
#' @param family Character: \code{"poisson"}, \code{"binomial"}, or
#'   \code{"gaussian"}.
#' @param Pi K x K misclassification matrix where \code{Pi[j, l] = P(Z_hat =
#'   j-1 | Z = l-1)}. Columns must sum to 1.
#' @param K Number of categories. Default: auto-detected.
#' @param lambda Numeric vector of SIMEX exponents (default: \code{c(0.5, 1,
#'   1.5, 2)}). These control the degree of additional misclassification added
#'   in the simulation step.
#' @param B Number of simulation replicates per lambda level (default: 200).
#' @param extrapolation Extrapolation method: \code{"quadratic"} (default),
#'   \code{"linear"}, or \code{"loglinear"}.
#' @param jackknife Logical or character. If \code{TRUE} or a string naming the
#'   extrapolation method for the variance, compute jackknife variance estimates.
#'   Default \code{TRUE} uses the same method as \code{extrapolation}.
#' @param freq_weights Optional frequency weights (length n, positive).
#' @param seed Random seed for reproducibility. Default: \code{42L}.
#'
#' @return An object of class \code{"mcsimex"} with components:
#'   \describe{
#'     \item{coefficients}{Named vector of SIMEX-corrected coefficients.}
#'     \item{naive}{Named vector of naive coefficients (lambda = 0).}
#'     \item{estimates}{Matrix of averaged estimates at each lambda level
#'       (rows = lambda levels including 0, cols = parameters).}
#'     \item{theta}{List of B x p matrices of raw simulation estimates,
#'       one per lambda level.}
#'     \item{extrapolation}{Fitted extrapolation model(s).}
#'     \item{lambda}{Lambda vector used (including 0).}
#'     \item{vcov}{Jackknife variance-covariance matrix (if requested).}
#'     \item{family, K, B, extrapolation_method}{Input parameters.}
#'   }
#'
#' @details
#' The MC-SIMEX algorithm proceeds in two steps:
#'
#' \strong{Simulation step}: For each \eqn{\lambda} in the lambda grid, the
#' misclassification matrix is raised to the power \eqn{\lambda} via
#' eigendecomposition (\eqn{\Pi^\lambda = V \Lambda^\lambda V^{-1}}), and B
#' replicates of the misclassified covariate are generated by sampling from the
#' columns of \eqn{\Pi^\lambda}. A GLM is refitted to each replicate, producing
#' B coefficient vectors per lambda level. The entire simulation+refitting loop
#' runs in compiled C++ code using Eigen for linear algebra and a built-in IRLS
#' solver.
#'
#' \strong{Extrapolation step}: The averaged coefficient estimates are plotted
#' against lambda and extrapolated to \eqn{\lambda = -1} (corresponding to no
#' misclassification). Supported extrapolation functions:
#' \itemize{
#'   \item \code{"linear"}: \eqn{\theta(\lambda) = \gamma_0 + \gamma_1 \lambda}
#'   \item \code{"quadratic"}: \eqn{\theta(\lambda) = \gamma_0 + \gamma_1 \lambda + \gamma_2 \lambda^2}
#'   \item \code{"loglinear"}: \eqn{\theta(\lambda) = \exp(\gamma_0 + \gamma_1 \lambda)}
#' }
#'
#' @references
#' Küchenhoff, H., Mwalili, S. M. and Lesaffre, E. (2006).
#' A general method for dealing with misclassification in regression: The
#' misclassification SIMEX. \emph{Biometrics}, 62(1), 85--96.
#'
#' @examples
#' set.seed(42)
#' n <- 5000
#' x <- cbind(1, rnorm(n))
#' z <- rbinom(n, 1, 0.4)
#' y <- rpois(n, exp(0.8 * z - 0.5 * x[, 1] + 0.7 * x[, 2]))
#'
#' p01 <- 0.10; p10 <- 0.15
#' z_hat <- z
#' z_hat[z == 0] <- rbinom(sum(z == 0), 1, p01)
#' z_hat[z == 1] <- 1 - rbinom(sum(z == 1), 1, p10)
#'
#' Pi <- matrix(c(1 - p01, p10, p01, 1 - p10), 2, 2)
#' fit <- mcsimex(y, z_hat, x, family = "poisson", Pi = Pi)
#' fit
#'
#' @export
mcsimex <- function(y, z_hat, x, family = "poisson",
                    Pi, K = NULL,
                    lambda = c(0.5, 1, 1.5, 2),
                    B = 200L,
                    extrapolation = c("quadratic", "linear", "loglinear"),
                    jackknife = TRUE,
                    freq_weights = NULL,
                    seed = 42L) {

  # --- input validation ---
  y     <- as.numeric(y)
  z_hat <- as.integer(z_hat)
  x     <- as.matrix(x)
  Pi    <- as.matrix(Pi)
  n     <- length(y)
  extrapolation <- match.arg(extrapolation)

  stopifnot(nrow(x) == n, length(z_hat) == n)

  if (is.null(K)) K <- nrow(Pi)
  stopifnot(nrow(Pi) == K, ncol(Pi) == K)
  stopifnot(all(z_hat >= 0L), all(z_hat < K))

  # Validate Pi columns sum to ~1
  col_sums <- colSums(Pi)
  if (any(abs(col_sums - 1) > 1e-6))
    stop("Columns of Pi must sum to 1 (got: ", paste(round(col_sums, 4), collapse = ", "), ")")

  lambda <- sort(as.numeric(lambda))
  B      <- as.integer(B)

  # Frequency weights
  if (is.null(freq_weights)) {
    wt <- rep(1.0, n)
  } else {
    wt <- as.numeric(freq_weights)
    stopifnot(length(wt) == n, all(wt > 0))
  }

  # Distribution code
  dist_code <- switch(family,
    gaussian = 1L, poisson = 2L, binomial = 3L,
    stop("Unsupported family: ", family)
  )

  # --- naive fit (lambda = 0) ---
  xi_hat <- build_xi_hat(z_hat, x, K)
  fam <- get_link_funs(family)
  dat <- data.frame(y = y, xi_hat)
  naive_fit <- stats::glm(y ~ . - 1, data = dat, family = fam$family,
                           weights = wt)
  psi_naive <- unname(stats::coef(naive_fit))
  p <- length(psi_naive)
  n_lambda <- length(lambda)

  # Parameter names
  if (K == 2L) {
    nms <- c("gamma", paste0("alpha", seq_len(ncol(x)) - 1))
  } else {
    nms <- c(paste0("gamma", seq_len(K - 1)),
             paste0("alpha", seq_len(ncol(x)) - 1))
  }
  names(psi_naive) <- nms

  # --- simulation step (C++) ---
  sim_result <- .Call("_mcGLM_mcsimex_sim_cpp",
    y, z_hat, x, Pi, K, dist_code, lambda, B, wt, as.integer(seed),
    PACKAGE = "mcGLM"
  )

  # Reshape: list of B x p matrices (one per lambda)
  theta_list <- vector("list", n_lambda)
  avg_estimates <- matrix(0, n_lambda, p)
  for (l in seq_len(n_lambda)) {
    rows <- ((l - 1) * B + 1):(l * B)
    theta_mat <- sim_result[rows, , drop = FALSE]
    colnames(theta_mat) <- nms
    theta_list[[l]] <- theta_mat
    avg_estimates[l, ] <- colMeans(theta_mat)
  }
  names(theta_list) <- paste0("lambda_", lambda)

  # Stack: lambda=0 (naive) + simulation averages
  all_lambda <- c(0, lambda)
  all_estimates <- rbind(psi_naive, avg_estimates)
  rownames(all_estimates) <- paste0("lambda_", all_lambda)
  colnames(all_estimates) <- nms

  # --- extrapolation step ---
  extrap_result <- extrapolate_simex(all_lambda, all_estimates, extrapolation)

  # --- jackknife variance ---
  vcov_jk <- NULL
  if (!isFALSE(jackknife)) {
    jk_method <- if (is.character(jackknife)) jackknife else extrapolation
    vcov_jk <- jackknife_variance(theta_list, psi_naive, naive_fit, lambda,
                                   jk_method, fam, xi_hat, y, wt)
    rownames(vcov_jk) <- colnames(vcov_jk) <- nms
  }

  out <- structure(
    list(
      coefficients        = extrap_result$coefficients,
      naive               = psi_naive,
      estimates           = all_estimates,
      theta               = theta_list,
      extrapolation       = extrap_result$model,
      lambda              = all_lambda,
      vcov                = vcov_jk,
      family              = family,
      K                   = K,
      B                   = B,
      n                   = n,
      p                   = p,
      extrapolation_method = extrapolation
    ),
    class = "mcsimex"
  )
  out
}


# ======================== EXTRAPOLATION ====================================

#' Extrapolate SIMEX estimates to lambda = -1
#' @keywords internal
extrapolate_simex <- function(lambda, estimates, method) {
  p <- ncol(estimates)
  nms <- colnames(estimates)
  coefs <- numeric(p)
  models <- vector("list", p)

  for (j in seq_len(p)) {
    y_j <- estimates[, j]
    dat <- data.frame(lambda = lambda, y = y_j)

    if (method == "linear") {
      fit <- stats::lm(y ~ lambda, data = dat)
    } else if (method == "quadratic") {
      fit <- stats::lm(y ~ lambda + I(lambda^2), data = dat)
    } else {
      # loglinear: y = exp(a + b*lambda)
      # log(y + offset) ~ lambda
      offset <- 0
      if (min(y_j) <= 0) offset <- abs(min(y_j)) + 1
      dat$y_adj <- log(y_j + offset)
      fit <- stats::lm(y_adj ~ lambda, data = dat)
      attr(fit, "loglinear_offset") <- offset
    }

    models[[j]] <- fit
    coefs[j] <- predict_at_minus1(fit, method)
  }

  names(coefs) <- nms
  list(coefficients = coefs, model = models)
}


#' Predict extrapolation model at lambda = -1
#' @keywords internal
predict_at_minus1 <- function(fit, method) {
  nd <- data.frame(lambda = -1)
  if (method == "loglinear") {
    offset <- attr(fit, "loglinear_offset")
    if (is.null(offset)) offset <- 0
    exp(stats::predict(fit, newdata = nd)) - offset
  } else {
    stats::predict(fit, newdata = nd)
  }
}


# ======================== JACKKNIFE VARIANCE ================================

#' Jackknife variance estimation for MC-SIMEX
#' @keywords internal
jackknife_variance <- function(theta_list, psi_naive, naive_fit,
                                lambda, jk_method, fam, xi_hat, y, wt) {
  p <- length(psi_naive)
  n_lambda <- length(lambda)
  N <- sum(wt)
  n <- length(y)

  # At each lambda, compute:
  #   Var_model = average model covariance across B replicates
  #   Var_sim   = empirical covariance of B coefficient vectors
  #   Var_jk    = Var_model - Var_sim

  # For the naive (lambda = 0): use the glm variance
  eta0 <- as.numeric(xi_hat %*% psi_naive)
  w0 <- fam$mu_dot(eta0)
  eps0 <- y - fam$mu(eta0)
  A0 <- crossprod(xi_hat * (wt * w0), xi_hat) / N
  C0 <- crossprod(xi_hat * (wt * eps0), xi_hat * eps0) / N
  A0_inv <- solve(A0)
  Var_naive <- A0_inv %*% C0 %*% A0_inv / N

  # Collect variance matrices at each lambda level
  # We approximate Var_model at each lambda by the sandwich from the mean estimate
  Var_jk_list <- vector("list", n_lambda)

  for (l in seq_len(n_lambda)) {
    theta_mat <- theta_list[[l]]  # B x p
    B_l <- nrow(theta_mat)

    # Empirical covariance of the B estimates
    Var_sim <- stats::cov(theta_mat) * (B_l - 1) / B_l  # population cov

    # Average model variance: approximate using sandwich at the mean estimate
    psi_mean <- colMeans(theta_mat)
    eta_m <- as.numeric(xi_hat %*% psi_mean)
    w_m <- fam$mu_dot(eta_m)
    eps_m <- y - fam$mu(eta_m)
    A_m <- crossprod(xi_hat * (wt * w_m), xi_hat) / N
    C_m <- crossprod(xi_hat * (wt * eps_m), xi_hat * eps_m) / N
    A_m_inv <- tryCatch(solve(A_m), error = function(e) MASS::ginv(A_m))
    Var_model <- A_m_inv %*% C_m %*% A_m_inv / N

    Var_jk_list[[l]] <- Var_model - Var_sim
  }

  # Stack variance elements and extrapolate each to lambda = -1
  # Vectorize: p*(p+1)/2 unique elements
  all_lambda <- c(0, lambda)
  n_elem <- p * p
  var_matrix <- matrix(0, n_lambda + 1, n_elem)
  var_matrix[1, ] <- as.numeric(Var_naive)
  for (l in seq_len(n_lambda)) {
    var_matrix[l + 1, ] <- as.numeric(Var_jk_list[[l]])
  }

  # Extrapolate each element
  var_simex <- numeric(n_elem)
  for (j in seq_len(n_elem)) {
    dat <- data.frame(lambda = all_lambda, y = var_matrix[, j])
    if (jk_method == "linear") {
      fit <- stats::lm(y ~ lambda, data = dat)
    } else if (jk_method == "quadratic") {
      fit <- stats::lm(y ~ lambda + I(lambda^2), data = dat)
    } else {
      offset <- 0
      if (min(dat$y) <= 0) offset <- abs(min(dat$y)) + 1
      dat$y <- log(dat$y + offset)
      fit <- stats::lm(y ~ lambda, data = dat)
      attr(fit, "loglinear_offset") <- offset
    }
    var_simex[j] <- predict_at_minus1(fit, jk_method)
  }

  matrix(var_simex, p, p)
}


# ======================== S3 METHODS =======================================

#' @export
print.mcsimex <- function(x, digits = 4, ...) {
  cat("MC-SIMEX estimator\n")
  cat(sprintf("  Family: %s, K = %d, B = %d, extrapolation = %s\n",
              x$family, x$K, x$B, x$extrapolation_method))
  cat(sprintf("  n = %d, p = %d\n\n", x$n, x$p))

  est <- rbind(x$naive, x$coefficients)
  rownames(est) <- c("Naive", "SIMEX")
  print(round(est, digits))
  invisible(x)
}

#' @export
coef.mcsimex <- function(object, ...) {
  object$coefficients
}

#' @export
vcov.mcsimex <- function(object, ...) {
  object$vcov
}

#' @export
summary.mcsimex <- function(object, ...) {
  cat("MC-SIMEX estimator\n")
  cat(sprintf("  Family: %s, K = %d, B = %d\n", object$family, object$K, object$B))
  cat(sprintf("  Extrapolation: %s\n", object$extrapolation_method))
  cat(sprintf("  Lambda grid: %s\n", paste(object$lambda, collapse = ", ")))
  cat(sprintf("  n = %d, p = %d\n\n", object$n, object$p))

  cat("Estimates at each lambda level:\n")
  print(round(object$estimates, 6))

  cat("\nSIMEX-corrected coefficients:\n")
  if (!is.null(object$vcov)) {
    se <- sqrt(pmax(diag(object$vcov), 0))
    tab <- cbind(Estimate = object$coefficients, `Std.Error` = se,
                 `z value` = object$coefficients / se,
                 `Pr(>|z|)` = 2 * stats::pnorm(-abs(object$coefficients / se)))
    stats::printCoefmat(tab, digits = 6)
  } else {
    print(round(object$coefficients, 6))
  }

  invisible(object)
}
