# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcsimex_sim_cpp <- function(y_r, z_hat_r, x_r, Pi_r, K, dist_code, lambda_r, B, wt_r, seed) {
    .Call(`_mcGLM_mcsimex_sim_cpp`, y_r, z_hat_r, x_r, Pi_r, K, dist_code, lambda_r, B, wt_r, seed)
}

